<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Promise </title>
<style>
    
</style>
</head>
<body>

<script>
/*    
    A Promise is an object representing the eventual completion or failure of an asynchronous operation.

    Below we see the consumption of returned promises

    ===== Guarantees
     A promise comes with some guarantees:
    1. Callbacks will never be called before the completion of the current run 
    of the JavaScript event loop.

    2. Callbacks added with .then even after the success or failure of the asynchronous 
    operation, will be called, as above.

    3. Multiple callbacks may be added by calling .then several times, 
    to be executed independently in insertion order.

    But the most immediate benefit of promises is chaining.

    ===== Chaining
    A common need is to execute two or more asynchronous operations back to back, 
    where each subsequent operation starts when the previous operation succeeds, 
    with the result from the previous step. We accomplish this by creating a promise chain.

    doSomething()
    .then(result => doSomethingElse(result))
    .then(newResult => doThirdThing(newResult))
    .then(finalResult => {
    console.log(`Got the final result: ${finalResult}`);
    })
    .catch(failureCallback);

    ===== Error propagation
    Basically, a promise chain stops if there's an exception, looking down the chain
    for catch handlers instead.
    This symmetry with synchronous code culminates in the async/await syntactic sugar in ECMAScript 2017:

    async function foo() {
        try {
            const result = await doSomething();
            const newResult = await doSomethingElse(result);
            const finalResult = await doThirdThing(newResult);
            console.log(`Got the final result: ${finalResult}`);
        } catch(error) {
            failureCallback(error);
        }
    }
    
*/

new Promise((resolve, reject) => {
    console.log('Initial');

    resolve();
})
.then(() => {
    throw new Error('Something failed');
        
    console.log('Do this');
})
.catch(() => {
    console.log('Do that');
})
.then(() => {
    console.log('Do this whatever happened before');
});

//This will output the following text:

//Initial
//Do that
//Do this whatever happened before


    

    
</script>    
</body>
</html>

